accounts/urls.py
from django.conf.urls import url

from django.contrib.auth import views as django_views

from . import views

urlpatterns = [
    url(r'^registration/$', views.registration_page, name='registration'),
    url(r'^activation/(?P<token>[\w]+)/$', views.activation_view, name='activation'),
    url(r'^password-reset-link/(?P<token>[\w]+)/$', views.activation_view, name='password_reset_link'),
    url(r'^profile/$', views.profile_view, name='profile'),
    url(r'^login/$', django_views.login, name='login'),
    url(r'^logout/$', django_views.logout, name='logout'),
    url(r'^restore/$', views.restore_password, name='restore_password'),
    url(r'^restore-send-email/$', views.restore_send_email, name='restore_send_email'),
    # url(r'^password-reset-link/(?P<token>[\w]+)/$', views.password_reset_link, name='password_reset_link'),
    url(r'^restore-send-sms/$', views.restore_send_sms, name='restore_send_sms'),
    url(r'^password_confirm_code/$', views.password_confirm_code, name='password_confirm_code'),
    # url(r'^password-reset-email/done/$', django_views.password_reset_done, name='password_reset_done'),
    url(r'^logout-then-login/$', django_views.logout_then_login, name='logout_then_login'),
    url(r'^reset-password/$', views.reset_password, name='reset_password'),
    url(r'^add-subscriber/$', views.add_subscriber, name='add_subscriber'),
    url(r'^upload-image/$', views.upload_image, name='upload_image'),
    url(r'^add-review/$', views.add_review, name='add_review'),
    url(r'^show-subscriptions/$', views.show_subscriptions, name='show_subscriptions'),
    url(r'^user-search/$', views.user_search, name='user_search'),
    url(r'^snap-card/$', views.snap_card, name='snap_card')
]

cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add-to-cart/$', views.add_to_cart, name='add_to_cart'),
    url(r'^cart-detail/$', views.cart_detail, name='cart_detail'),
    url(r'^remove-from-cart/$', views.remove_from_cart, name='remove_from_cart'),
    url(r'^showcase-detail/$', views.show_showcase, name='showcase_detail'),
]

chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^thread-list/$', views.show_threads_list, name='show_thread_list'),
    url(r'^send-message/$', views.send_message, name='send_message'),
    url(r'^thread/(?P<thread_id>\d+)/$', views.show_thread, name='show_thread'),
    url(r'^send_message_api/$', views.send_message_api, name='send_message_api'),
    url(r'^check_username/$', views.check_username, name='check_username'),
    url(r'^send_message_ajax/$', views.send_message_ajax, name='send_message_ajax'),
]

goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^search/$', views.search_view, name='search'),
    url(r'^modal/(?P<good_pk>\d+)/$', views.goods_modal, name='goods_modal'),
    url(r'^good/(?P<good_pk>\d+)/$', views.good_view, name='good_view'),
    url(r'^add-to-wishlist/$', views.add_to_wishlist, name='add_to_wishlist'),
    url(r'^add-user-like/$', views.add_user_like, name='add_user_like'),
    url(r'^goods-filter/$',views.goods_filter, name='goods_filter'),
    url(r'^add-new-tag/$', views.add_new_tag, name='add_new_tag'),
    url(r'^add/$', views.add_good, name='add_good'),
    url(r'^edit/(?P<good_pk>\d+)/$', views.edit_good, name='edit_good'),
    url(r'^delete/(?P<pk>\d+)/$', views.GoodDeleteView.as_view(), name='delete_good'),
    url(r'^upload-good-photo/$', views.upload_good_photo, name='upload_good_photo'),
    url(r'^delete-good-photo/$', views.delete_photo, name='delete_good_photo'),
    url(r'^wishlist/$', views.show_wishlist, name='show_wishlist'),
    url(r'^add-bid/$', views.add_auction_bid, name='add_bid'),
    url(r'^remove-bid/$', views.reject_auction_bid, name='reject_bid'),
    url(r'^disable-good/$', views.set_inactive_good, name='disable-good'),
    url(r'^accept-bid/$', views.accept_bid, name='accept-bid')
]

main/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^for-business/$', views.for_biz_view, name='for_biz_view'),
    url(r'^advertising/$', views.advertising, name='advertising'),
    url(r'^rules/$', views.rules, name='rules'),
    url(r'^privacy/$', views.privacy, name='privacy'),
    url(r'^calculator/$', views.calculator_view, name='calculator')
]

storesb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from filebrowser.sites import site

from storesb.settings import MEDIA_ROOT, MEDIA_URL

from main.views import index_view
from accounts.views import user_page

from django.conf import settings
from django.contrib.staticfiles.views import serve as serve_static
from django.views.decorators.cache import never_cache


urlpatterns = [
    url(r'^$', index_view, name='index'),
    url(r'^main/', include('main.urls', namespace='main', app_name='main')),
    url(r'^goods/', include('goods.urls', namespace='goods', app_name='goods')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
    url(r'^complaints/', include('complaints.urls', namespace='complaints', app_name='complaints')),
    url(r'^chat/', include('chat.urls', namespace='chat', app_name='chat')),
    url(r'^cart/', include('cart.urls', namespace='cart', app_name='cart')),
    url('^pages/', include('pages.urls', namespace='pages', app_name='pages')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'social-auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^(?P<user_slug>\w+)/$', user_page, name='user_page'),

    url(r'^static/(?P<path>.*)$', never_cache(serve_static))
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from taggit.models import Tag

from main.models import BaseModel
from main.countries_list import COUNTRIES
from goods.models import Good

from .constants import LIME, ORANGE, NOT_DEFINED, PRIVATE_PERSON, LEGAL_ENTITY, MALE, FEMALE, VK, FACEBOOK, PINTEREST
from .constants import TWITTER, ODNOKLASSNIKI, ONLINE, OFFLINE

# Create your models here.


class SocialNetwork(BaseModel):
    """
    SocialNetwork model. Store access tokens and name of soc. networks.
    """
    NETWORKS = (
        (VK, "vKontakte"),
        (FACEBOOK, "Facebook"),
        (PINTEREST, "Pinterest"),
        (TWITTER, "Twitter"),
        (ODNOKLASSNIKI, "Odnoklassniki")
    )
    title = models.CharField(max_length=100, verbose_name=_("Title"))
    network_id = models.CharField(choices=NETWORKS, verbose_name=_('Network ID'), unique=True, null=True, blank=True,
                                  max_length=20)

    def __str__(self):
        return self.title
#
#
# class SocialAccount(BaseModel):
#     """
#     User social accounts. Store link to user social network page and setting to post on his page.
#     """
#     user = models.OneToOneField(User, related_name="social_account")
#     social_network = models.ForeignKey(SocialNetwork, verbose_name=_("Social network"))
#     account_link = models.CharField(max_length=255, null=True, blank=True, verbose_name=_("Account link"))
#     auto_post_updated = models.BooleanField(default=False, verbose_name=_("Auto post"))
#
#     def __str__(self):
#         return self.user.username


class UserProfile(BaseModel):
    """
    User profile.
    """
    ORG_FORM = (
        (PRIVATE_PERSON, _("Private person")),
        (LEGAL_ENTITY, _("Legal entity")),
        # (2, _("Individual entrepreneur"))
    )
    SEX = (
        (MALE, _('MALE')),
        (FEMALE, _('FEMALE')),
        (NOT_DEFINED, _('NOT DEFINED'))
    )
    USER_THEME = (
        (LIME, _("LIME")),
        (ORANGE, _("ORANGE")),
        (NOT_DEFINED, _("NOT DEFINED"))
    )
    STATUS = (
        (OFFLINE, _("Offline")),
        (ONLINE, _("Online"))
    )

    user = models.OneToOneField(User, related_name="profile")
    avatar = models.ImageField(upload_to='avatars', blank=True, null=True, verbose_name=_("Avatar"))
    cover = models.ImageField(upload_to='covers', blank=True, null=True, verbose_name=_("Cover"))
    description = models.TextField(null=True, blank=True, verbose_name=_("About"))
    sex = models.IntegerField(choices=SEX, default=2, verbose_name=_("SEX"))
    org_form = models.IntegerField(choices=ORG_FORM, default=0, verbose_name=_("Form of incorporation"))
    country = models.CharField(max_length=3, verbose_name=_("Country"), choices=COUNTRIES, default='RU')
    city = models.CharField(max_length=255, null=True, blank=True, verbose_name=_("City"))
    phone = models.CharField(verbose_name=_("Phone"), null=True, blank=True, max_length=20)
    additional_phone = models.CharField(verbose_name=_("Additional phone"), null=True, blank=True, max_length=20)
    skype = models.CharField(max_length=255, null=True, blank=True, verbose_name="Skype")
    instagram = models.CharField(max_length=255, null=True, blank=True, verbose_name="Instagram")
    site = models.CharField(verbose_name="Web site", null=True, blank=True, max_length=128)
    map_link = models.TextField(verbose_name=_("Google map link"), null=True, blank=True)
    slug = models.SlugField(max_length=255, verbose_name=_("Profile link"), unique=True)
    theme = models.IntegerField(choices=USER_THEME, default=2, verbose_name=_("Theme"))
    status = models.IntegerField(choices=STATUS, default=OFFLINE, verbose_name=_("User online status"))
    auto_post_to_networks = models.ManyToManyField(SocialNetwork, verbose_name=_('Allow auto post to'))

    def avatar_tag(self):
        return u'<img src="%s" height=75 width=75 />' % (self.avatar.url)

    avatar_tag.short_description = _("Current avatar")
    avatar_tag.allow_tags = True

    def __str__(self):
        return self.user.username

    def get_all_about_marks(self):
        marks = Reviews.objects.filter(about_user=self.user).values_list('mark', flat=True)
        return marks

    def get_my_marks(self):
        marks = Reviews.objects.filter(author=self.user).values_list('mark', flat=True)
        return marks

    def get_absolute_url(self):
        return reverse('user_page', args=[self.slug])

    def get_mark_count_about(self, mark):
        marks_count = Reviews.objects.filter(about_user=self.user).filter(mark=mark).count()
        return marks_count

    def get_about_average_mark(self):
        marks = self.get_all_about_marks()
        avg = 0
        sum = 0
        if len(marks) > 0:
            for mark in marks:
                sum += mark
            avg = sum / len(marks)
        return avg

    def get_total_about_marks(self):
        marks_count = Reviews.objects.filter(about_user=self.user).count()
        return marks_count

    def get_lots_count(self):
        lots_count = self.user.goods.count()
        return lots_count

    def get_subscribers_count(self):
        count_lists = Subscribers.objects.filter(users=self.user).count()
        return count_lists

    def get_subscription_count(self):
        try:
            my_list = Subscribers.objects.get(owner=self.user)
            count = my_list.users.count()
        except:
            count = 0
        return count

    def get_user_tags(self):
        """
        Get all user tags
        :return:
        """
        goods = Good.objects.filter(user=self.user)
        tags = Tag.objects.filter(good__in=goods).distinct()
        return tags

    class Meta:
        ordering = ('updated',)


class ActivationProfile(models.Model):
    """
    Model to store email token or sms code for registration.
    """
    user = models.ForeignKey(User)
    token = models.CharField(max_length=255)
    sms_key = models.CharField(max_length=10)
    valid_through = models.DateTimeField()
    password_reset = models.BooleanField(default=False)


class UserComments(BaseModel):
    """

    """
    about_user = models.ForeignKey(User, related_name='about_comments')
    user = models.ForeignKey(User, related_name='users_comments')
    text = models.TextField(verbose_name=_('Comment'))

    def __str__(self):
        return self.about_user.title

    class Meta:
        ordering = ('created',)


class Subscribers(BaseModel):
    """

    """
    owner = models.OneToOneField(User, related_name='subscribers')
    users = models.ManyToManyField(User, related_name='subscriptions')

    def __str__(self):
        return self.owner.username

    class Meta:
        ordering = ('created',)


class Reviews(BaseModel):
    """

    """
    MARKS = (
        (0, 0),
        (0.5, 0.5),
        (1, 1),
        (1.5, 1.5),
        (2, 2),
        (2.5, 2.5),
        (3, 3),
        (3.5, 3.5),
        (4, 4),
        (4.5, 4.5),
        (5, 5)
    )
    about_user = models.ForeignKey(User, related_name='reviews')
    author = models.ForeignKey(User, related_name='my_reviews')
    text = models.TextField(verbose_name=_('Text'))
    mark = models.DecimalField(choices=MARKS, default=0, max_digits=3, decimal_places=1)

    def __str__(self):
        return self.about_user.username + ' ' + str(self.mark)

    class Meta:
        ordering = ('created',)


class CardData(BaseModel):
    user = models.ForeignKey(User, related_name='cards', verbose_name=_('User'))
    number = models.BigIntegerField(verbose_name=_('Card number'))
    valid_throgh_month = models.IntegerField(verbose_name=_('Month'))
    valid_throgh_year = models.IntegerField(verbose_name=_('Year'))

    def __str__(self):
        return self.user.username + ' ' + 'card'

    class Meta:
        ordering = ('updated', )

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from main.countries_list import COUNTRIES

from .models import UserProfile, SocialNetwork


class UserRegistrationForm(forms.Form):
    """
    User registration form.
    """
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': "E-mail"}), required=False)
    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder': _("Your mobile phone number")}), required=False)
    confirm_code = forms.CharField(widget=forms.TextInput(attrs={'placeholder': _("Confirm code")}), required=False)
    accept = forms.BooleanField(required=True, label=_("I agree to the user agreement"))

    def clean_phone(self):
        cd = self.cleaned_data
        phone = cd['phone']
        if phone:
            if len(phone) < 10 or not phone.isdigit():
                raise forms.ValidationError(_("Your phone should be in format 79994567891 or 89994567891"))
        return cd['phone']


class PasswordResetEmailForm(forms.Form):
    """
    Form to enter email for password reset.
    """
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': "E-mail"}))


class PasswordResetPhoneForm(forms.Form):
    """
    Form to enter phone for password reset.
    """
    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder': _("Your mobile phone number")}))

    def clean_phone(self):
        cd = self.cleaned_data
        phone = cd['phone']
        if phone:
            if len(phone) < 10 or not phone.isdigit():
                raise forms.ValidationError(_("Your phone should be in format 79994567891 or 89994567891"))
        return cd['phone']


class PasswordResetConfirmPhoneForm(forms.Form):
    """
    Form to enter sms code for password reset.
    """
    confirm_code = forms.CharField(widget=forms.TextInput(attrs={'placeholder': _("Confirm code")}))


class UserEditForm(forms.ModelForm):
    """
    Form to edit user's username and email
    """
    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileEditForm(forms.ModelForm):
    """
    Forms to edit user profile
    """
    org_form = forms.ChoiceField(choices=UserProfile.ORG_FORM, widget=forms.RadioSelect())
    sex = forms.ChoiceField(choices=UserProfile.SEX, widget=forms.RadioSelect())
    auto_post_to_networks = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, required=False,
                                                           queryset=SocialNetwork.objects.all())

    class Meta:
        model = UserProfile
        exclude = ['user', 'avatar', 'cover' , 'theme', 'status', 'map_link']
        widgets = {
            'description': forms.Textarea(attrs={'cols': 30, 'rows': 10})
        }


class SetNewPassword(forms.Form):
    """
    Set password form. Used on reset/set first password on activation.
    """
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError("Password's don't match.")
        # At least MIN_LENGTH long
        if len(cd['password2']) < 8:
            raise forms.ValidationError(_("The new password must be at least %d characters long.") % 8)
        # At least one letter and one non-letter
        first_isalpha = cd['password2'][0].isalpha()
        if all(c.isalpha() == first_isalpha for c in cd['password2']):
            raise forms.ValidationError(_("""
                The new password must contain at least one letter and at least one digit or punctuation character."""))
        return cd['password2']

accounts/templates/account.html
{% extends 'basis.html' %}
{% load i18n %}
{% load staticfiles %}
{% load main_tags %}
{% block title %}{% trans 'Edit your account' %}{% endblock %}
{% block scripts %}
<link rel="stylesheet" type="text/css" href="/static/css/account/account.css">
{#    <script type="text/javascript" src="{% static 'js/calc.js' %}"></script>#}
<script type="text/javascript" src="{% static 'js/account/settings.js' %}"></script>
{% endblock %}
{% block content %}
<div class="sixteen wide center aligned column" id="infobar"><h5>{% trans 'Account settings' %}</h5></div>
				{% if messages %}
        <div class="sixteen wide center aligned column padless">
        		{% for message in messages %}
            		<h5 class="ui red header">{{ message }}</h5>
        		{% endfor %}
				</div>
    		{% endif %}
        <div class="sixteen wide center aligned column padless">
            <h5 class="ui header">{% trans 'Welcome' %} {{ request.user.username }}!</h5>
        </div>
    <div class="sixteen wide column padless">
        <form class="ui form" action="." method="post">
				{% csrf_token %}
        <div class="ui segment grid">
            <div class="sixteen wide center aligned column">
                <h4>{% trans 'Profile' %}</h4>
            </div>
            <div class="two wide column"></div>
            <div class="three wide left aligned column">
                <h5>{% trans 'Username' %}</h5>
                <h5>E-mail</h5>
                <h5>{% trans 'Phone' %}</h5>
                <h5>{% trans 'Additional phone' %}</h5>
                <h5>Skype</h5>
                <h5>Instagram</h5>
                <h5>{% trans 'Web-site' %}</h5>
                <h5>{% trans 'Country' %}</h5>
                <h5>{% trans 'City' %}</h5>
                <h5>{% trans 'You are?' %}</h5>
                <h5>{% trans 'Sex' %}</h5>
            </div>
            <div class="one wide column"></div>
            <div class="nine wide right aligned column accurate_fields">
                <div class="field">
                    {{ user_edit_form.username }}{{ user_edit_form.username.errors.as_text }}
                </div>
                <div class="field">
                    {{ user_edit_form.email }}{{ user_edit_form.email.errors.as_text }}
                </div>
                <div class="field">
                    {{ profile_edit_form.phone }}{{ profile_edit_form.phone.errors.as_text }}
                </div>
                <div class="field">
                    {{ profile_edit_form.additional_phone }}{{ profile_edit_form.additional_phone.errors.as_text }}
                </div>
                <div class="field">
                    {{ profile_edit_form.skype }}{{ profile_edit_form.skype.errors.as_text }}
                </div>
                <div class="field">
                    {{ profile_edit_form.instagram }}{{ profile_edit_form.instagram.errors.as_text }}
                </div>
                <div class="field">
                    {{ profile_edit_form.site }}{{ profile_edit_form.site.errors.as_text }}
                </div>
                <div class="field">
                    {{ profile_edit_form.country }}
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        {{ profile_edit_form.city }}{{ profile_edit_form.city.errors.as_text }}
                    <i class="marker icon"></i>
                    </div>
                </div>
                <div class="two inline fields equal">
										{% for radio in profile_edit_form.org_form %}
                    <div class="field radiocust olive">
                    		{{ radio.tag }}
                    		<label for="{{ radio.id_for_label }}">{{ radio.choice_label }}</label>
                    </div>
                		{% endfor %}
                </div>
                <div class="three inline fields accurate equal">
									{% for radio in profile_edit_form.sex %}
                	<div class="field radiocust olive">
                    	{{ radio.tag }}
                    	<label for="{{ radio.id_for_label }}">{{ radio.choice_label }}</label>
                	</div>
                	{% endfor %}
                </div>
            </div>
        </div>
        <div class="ui segment grid">
            <div class="sixteen wide center aligned column">
                <h4>{% trans 'Information' %}</h4>
            </div>
            <div class="two wide column"></div>
            <div class="three wide left aligned column">
                <h5>{% trans 'About' %}</h5>
            </div>
            <div class="one wide column"></div>
            <div class="nine wide right aligned column">
                <div class="field">
                		{{ profile_edit_form.description }}
                		{{ profile_edit_form.description.errors.as_text }}
                </div>
            </div>
        </div>
        <div class="ui segment grid">
        <!-- Social networks block -->
            <div class="sixteen wide center aligned column">
                <h4>{% trans 'Automaticly publish in' %}</h4>
            </div>
            <div class="two wide center aligned column"></div>
								{% for network in profile_edit_form.auto_post_to_networks %}
									<div class="four wide center aligned column">
                   	<div class="checkcust olive">
                  	  {{ network.tag }}
                    	<label for="{{ network.id_for_label }}" class="interface"><i class="{% if network.choice_label == 'vkontakte' %}vk{% else %}{{ network.choice_label }}{% endif %} icon"></i>{{ network.choice_label }}</label>
								    </div>
                	</div>
                {% endfor %}
                <!--<div class="four wide center aligned column">
                    <div class="checkcust olive">
                        <input type="checkbox" name="auto_post_to_networks" id="id_auto_post_to_networks_0" value="1">
                        <label for="id_auto_post_to_networks_0" class="interface"><i class="facebook icon"></i>Facebook</label>
                    </div>
                </div>
                <div class="four wide center aligned column">
                    <div class="checkcust olive">
                        <input type="checkbox" name="auto_post_to_networks" id="id_auto_post_to_networks_1" value="2">
                        <label for="id_auto_post_to_networks_1" class="interface"><i class="vk icon"></i>vKontakte</label>
                    </div>
                </div>
                <div class="two wide center aligned column">
                    <div class="checkcust olive">
                        <input type="checkbox" name="twitter" id="twitter">
                        <label for="twitter" class="interface">Twitter</label>
                    </div>
                </div>
                <div class="four wide center aligned column">
                    <div class="checkcust olive">
                        <input type="checkbox" name="auto_post_to_networks" id="id_auto_post_to_networks_2" value="3">
                        <label for="id_auto_post_to_networks_2" class="interface"><i class="pinterest icon"></i>Pinterest</label>
                    </div>
                </div>-->
            <div class="two wide center aligned column"></div>
        </div>
        <!-- End social networks block -->
        <div class="ui segment grid">
            <div class="sixteen wide center aligned column">
                <h4>{% trans 'Your page addree' %}</h4>
            </div>
            <div class="two wide column"></div>
            <div class="three wide left aligned column">
                <h5>{% trans 'Page address' %}</h5>
            </div>
            <div class="one wide column"></div>
            <div class="nine wide right aligned column">
                <div class="inline fields">
										STORESB.COM/
                    <div class="sixteen wide field paddless" data-tooltip="{% blocktrans %}
                        You can change the short address of your page to a convenient and memorable.
                        To do this, enter the page name consisting of letters, numbers or symbols '_'.
                    {% endblocktrans %}">
												{{ profile_edit_form.slug }}
                    </div>
                </div>
            </div>
        </div>
        <div class="ui segment grid">
            <div class="sixteen wide center aligned column">
                <h4>{% trans 'Account' %}</h4>
            </div>
            <div class="seven wide center aligned column"></div>
            <div class="two wide center aligned column">
                <input type="submit" class="ui small olive fluid button" value="EDIT" name="edit"><br>
                <a href="{% url 'accounts:logout' %}" class="ui small grey basic fluid button">LOGOUT</a></div>
            <div class="seven wide center aligned column"></div>
        </div>
        </form>
        <form action="." method="post" class="ui form">
				{% csrf_token %}
        <div class="ui segment grid">
            <div class="sixteen wide center aligned column">
                <h4>{% trans 'Change password' %}</h4>
            </div>
            <div class="two wide column"></div>
            <div class="three wide left aligned column">
                <h5>{% trans 'Current password' %}</h5>
                <h5>{% trans 'New password' %}</h5>
                <h5>{% trans 'Confirm password' %}</h5>
            </div>
            <div class="one wide column"></div>
            <div class="nine wide right aligned column">
                <div class="field">
                    {{ password_form.old_password }}{{ password_form.old_password.errors.as_text }}
                </div>
                <div class="field">
                    <div class="ui left icon input">
                    <i id="showpass" class="hide link icon"></i>
                    {{ password_form.new_password1 }}{{ password_form.new_password1.errors.as_text }}
                    </div>
                </div>
                <div class="field">
                    {{ password_form.new_password2 }}{{ password_form.new_password2.errors.as_text }}
                </div>
            </div>
            <div class="seven wide center aligned column"></div>
            <div class="two wide center aligned column">
                <input class="ui small olive fluid button" type="submit" value="OK" name="password">
            </div>
            <div class="seven wide center aligned column"></div>
        </div>
    		</form>
        <div style="text-align: center">
            <a href="{% url 'accounts:restore_password' %}" class="recovery-pass">Did you forget your account or password?</a>
        </div>
    </div>
{% endblock %}
<header class="black">
		<ul>
			<li><div></div></li>
			<li>
                <a href="{% url 'accounts:show_subscriptions' %}"></a>
                {{ request.user|show_count_subscriptions|safe }}
            </li>
			<li>
                <a href="#"></a>
                <span>258</span>
            </li>
			<li>
                <a href="{% url 'chat:show_thread_list' %}"></a>
                {{ request.user|show_unread_message_count|safe }}
            </li>
			<li>
                <a href="{% url 'goods:show_wishlist' %}"></a>
                {{ request.user|show_count_goods_in_wishlist|safe }}
            </li>
			<li>
                <a href="{{ request.user.profile.get_absolute_url }}"></a>
            </li>
			<li>
                <a href="{% url 'main:calculator' %}"></a>
            </li>
			<li>
                <a href="{% url 'accounts:user_search' %}"></a>
            </li>
			<li>
                <a href="#"></a>
                <span>258</span>
            </li>
			<li><a href="{% url 'accounts:profile' %}"></a></li>
			<li>